import type { Metadata } from "next";
import Footer from "./components/footer";
import Navbar from "./components/navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Skinhouse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  // eslint-disable-next-line no-undef
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-light-alabaster text-light-blacktext font-Basier flex flex-col w-full h-full pt-16 pb-4 px-[5%]">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
